=head1 NAME

qsorep -  logging with ADIF-files

=head1 SYNOPSIS

B<qsorep> [B<-c> command] [B<-h>] [B<-v>] [B<-V>]

=head1 DESCRIPTION

The B<qsorep> can be used to add or edit QSOs in an ADIF-file. The log can 
be merged with the main log file. New QSOs and QSLs from LoTW can be fetched
and merged. Production of QSL labels or QSL cards is possible. Use for
example B<git> to track changes in the log files.

=head1 OPTIONS

B<-c> execute command string

B<-h> display a short help text

B<-v> verbose

B<-V> print version

=head1 COMMANDS



=head1 EXAMPLE

Create initial local copy of LoTW QSOs

I<lotw> B<create> B<LoTW>

Print info on the I<lotw.adi> file

I<lotw> B<info>

Update received QSLs from LoTW and merge them to the main log file

I<lotw> B<qsl> B<merge>

Edit main log file

I<log> B<edit>

Add QSO to I<mycall> log file

I<mycall> B<add> ZX9ABC 14.0432 CW 599/449 John

Add QSOs from received paper QSL cards by call signs and merge with the main
log file

I<qsl> B<add> AB9XYZ CD8ZYX ...

I<qsl> B<merge> B<test>

I<qsl> B<merge>

Print QSL card file and mark the cards as sent in the main log

I<qsl> B<card> 

I<qsl> B<merge>

=head1 DIAGNOSTICS

The I<qsorep> has been tested with perl v5.10.1. You may need to adapt 
the script to your environment. 

=head1 BUGS

=head1 AUTHORS

Jaakko Koivuniemi OH7BF, if tod lars ta fb7ho

=head1 LINKS

=head1 SEE ALSO

Getopt::Std(3pm), Term::ReadLine(3pm), adifmerg(1)
